### PR TITLE
refactor: Replace ethers Event with Log

### PR DESCRIPTION
**Pull request by pxrl**
This follows a similar change in the SDK, with the same motivations. Reverting to Log instead of Event does not sacrifice any functionality but makes it easier to migrate away from ethers v5.

### CODE REVIEW

**Comment by pxrl** [comment]
nb. This will currently fail until the upstream PR in the SDK is merged and a new release is produced (https://github.com/across-protocol/sdk/pull/738).

**Comment by pxrl** [comment]
I've tested this a bit with the `validateRootBundle.ts` script - it's successfully validating old bundles within the past few days OK.

**Review by nicholaspai — APPROVED** [review]
Seems like a simple type swap, LGTM

**Review by bmzig — APPROVED** [review]
I think this makes sense, especially since the only fields of `Event` we dropped to create `Log` were the ones we didn't use in the first place.

**Pull request merged**
