### PR TITLE
chore: Bump constants, contracts & sdk

### PR DESCRIPTION
**Pull request by pxrl**
For some RPC-related improvements & bugfixes, as well as:

- WBTC on Lisk.
- POOL on World Chain.
- USDC.e on Aleph Zero.

### CODE REVIEW

**Comment by pxrl** [comment]
Here's the delta from SDK v3.3.21 -> v3.3.24: https://github.com/across-protocol/sdk/compare/v3.3.21...v3.3.24.

**Review by james-a-morris — APPROVED** [review]

**Review by james-a-morris — COMMENTED** [review]
this fails tests

**Comment by pxrl** [comment]
> this fails tests

Yeah it's an annoying dependency issue. Seems that we need to bump contracts and uma/core at the same time.

**Comment by pxrl** [comment]
> > this fails tests
> 
> Yeah it's an annoying dependency issue. Seems that we need to bump contracts and uma/core at the same time.

I realised that the issues arise from this PR: https://github.com/across-protocol/relayer/pull/1941/commits/3d1e83d3b2ae5c3f3dfef87098105c3d39de1034

If I only bump constants, contracts & SDK then it builds OK. I force-pushed that here: https://github.com/across-protocol/relayer/pull/1941/commits/132f1f25d2b8cc5bbf9d5fc8ca731e99c638b60c

**Review by nicholaspai — APPROVED** [review]

**Pull request merged**
