### PR TITLE
feat: Support submitting private transactions

### PR DESCRIPTION
**Pull request by pxrl**
This change introduces the ability to define custom RPC providers to be used when submitting transactions. Custom providers are slotted under the PRIVACY namespace, since that's the anticipated use case for them.

This is held fairly generic within ProviderUtils by scoping the change as a generic namespace, rather than introducing any concept of privacy.

### CODE REVIEW

**Comment by pxrl** [comment]
Note: This is the most minimally-invasive way I could figure to introduce this feature. It's a little bit on the side of a kludge, but I expect it should be reliable enough and doesn't pollute the config syntax too badly, so hopefully it's something we can live with.

**Review by nicholaspai — COMMENTED** [review]
One note is that submitting to private RPCs might change how the txn client or multicaller client reports txn receipts. Can we test this out locally?

**Comment by pxrl** [comment]
> One note is that submitting to private RPCs might change how the txn client or multicaller client reports txn receipts. Can we test this out locally?

I've tested locally on mainnet and Sepolia and have added some additional logging to verify that the new provider is instantiated correctly. So far I haven't seen any difference in the transmission flow - it seems to work exactly as expected.

**Comment by pxrl** [comment]
Closing this for now; I saw too many transactions get blackholed during test.

**Pull request closed without merging**
