### PR TITLE
improve(Monitor): reformat reportRelayerBalances log

### PR DESCRIPTION
**Pull request by bmzig**
This change makes the logs from the monitor more readable by formatting the reported balances as a table.

### CODE REVIEW

**Comment by nicholaspai** [comment]
Can you give an example output? An image works

**Comment by bmzig** [comment]
Before: 
image
After:
image

**Comment by nicholaspai** [comment]
> Before: 
> 
> image
> 
> After:
> 
> image
> 
> 

Hm can this be rendered better? The columns don't line up vertically still

**Review by james-a-morris — COMMENTED** [review]
Will this report properly in slack?

**Comment by bmzig** [comment]
> > Before:
> > image
> > After:
> > image
> 
> Hm can this be rendered better? The columns don't line up vertically still

So as you know, the slack markdown support is pretty limited. I did not want to *overdo* it and check the length of each balance report to ensure that the columns are aligned, since that just seemed like it was a bit overkill, but that can be done if you think it's not overengineering this. Fwiw, I checked and slack can't render markdown tables or latex matrices.

**Comment by bmzig** [comment]
> Will this report properly in slack?

The screenshots taken are from slack (I don't know if that is what you meant by the question). I did not change any of the actual logic which calculates the balances -- I only made changes to how the output is formatted.

**Comment by bmzig** [comment]
Here is the updated look: 
image

**Review by james-a-morris — COMMENTED** [review]
Can you provide the updated slack readout?

**Review by james-a-morris — COMMENTED** [review]
How would this look for tokens where we have balances on the order of millions? Ie WETH

**Comment by bmzig** [comment]
> How would this look for tokens where we have balances on the order of millions? Ie WETH

image
image

It only really matters if all columns are maxed out with >7 figures when we might see some wrapping.

**Review by nicholaspai — APPROVED** [review]
Let's try it!

**Pull request merged**
